CREATE TABLE [dbo].[__DATAFIXTrxHeader1301024] (
    [TrxId]                INT                IDENTITY (1, 1) NOT NULL,
    [Version]              INT                NOT NULL,
    [DeviceId]             NVARCHAR (25)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TrxTypeId]            INT                NOT NULL,
    [TrxDate]              DATETIMEOFFSET (7) NOT NULL,
    [ClientId]             INT                NULL,
    [SiteId]               INT                NULL,
    [TerminalId]           NVARCHAR (25)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reference]            NVARCHAR (50)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OpId]                 NVARCHAR (100)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TrxStatusTypeId]      INT                NULL,
    [CreateDate]           DATETIME           NOT NULL,
    [TerminalDescription]  NVARCHAR (100)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BatchId]              NVARCHAR (100)     NULL,
    [Batch_Urn]            NVARCHAR (100)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TrxCommitDate]        DATETIMEOFFSET (7) NULL,
    [InitialTransaction]   INT                NULL,
    [DeviceIdentity]       INT                NULL,
    [CallContextId]        UNIQUEIDENTIFIER   NULL,
    [TerminalExtra]        NVARCHAR (100)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AccountCashBalance]   FLOAT (53)         NULL,
    [AccountPointsBalance] FLOAT (53)         NULL,
    [ImportUniqueId]       NVARCHAR (50)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EposTrxId]            BIGINT             NULL,
    [TerminalExtra2]       NVARCHAR (MAX)     NULL,
    [TerminalExtra3]       NVARCHAR (1000)    NULL,
    [MemberId]             INT                NULL,
    [TotalPoints]          FLOAT (53)         NULL,
    [OLD_TrxId]            INT                NULL,
    [LastUpdatedDate]      DATETIMEOFFSET (7) NULL,
    [IsAnonymous]          BIT                NULL,
    [ReservationId]        INT                NULL,
    [IsTransferred]        BIT                NULL,
    [ReceiptId]            INT                NULL,
    [Region]               NVARCHAR (100)     NULL,
    [Location]             NVARCHAR (100)     NULL
);

