CREATE TABLE [dbo].[__DeviceFIX] (
    [Id]                   INT            NOT NULL,
    [DeviceId]             NVARCHAR (25)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Version]              INT            NOT NULL,
    [DeviceStatusId]       INT            NOT NULL,
    [DeviceTypeId]         INT            NOT NULL,
    [UserId]               INT            NULL,
    [HomeSiteId]           INT            NOT NULL,
    [CreateDate]           DATETIME       NOT NULL,
    [Owner]                NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reference]            NVARCHAR (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmbossLine1]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmbossLine2]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmbossLine3]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmbossLine4]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmbossLine5]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Pin]                  NVARCHAR (4)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DeviceNumberPoolId]   INT            NULL,
    [ExpirationDate]       DATETIME2 (7)  NULL,
    [AccountId]            INT            NULL,
    [StartDate]            DATETIME2 (7)  NULL,
    [PinFailedAttempts]    INT            NOT NULL,
    [DeviceLotId]          INT            NULL,
    [ExtraInfo]            NVARCHAR (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LotSequenceNo]        NVARCHAR (12)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OLD_AccountID]        INT            NULL,
    [OLD_MemberID]         INT            NULL,
    [AssignedBy]           NVARCHAR (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Deleted]              BIT            NULL,
    [CVC]                  NVARCHAR (3)   NULL,
    [PINVerificationValue] NVARCHAR (5)   NULL,
    [ImageUrl]             NVARCHAR (500) NULL
);

