CREATE TABLE [SSISHelper].[Installers] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [UNIQUEid]              FLOAT (53)     NULL,
    [DATE ADDED]            NVARCHAR (20)  NULL,
    [DM2 Account Name]      NVARCHAR (255) NULL,
    [installer_name]        NVARCHAR (255) NULL,
    [installer_group]       NVARCHAR (50)  NULL,
    [Account #]             NVARCHAR (255) NULL,
    [Branch Code]           NVARCHAR (255) NULL,
    [Sales Rep]             NVARCHAR (255) NULL,
    [contact_name]          NVARCHAR (255) NULL,
    [contact_email_address] NVARCHAR (255) NULL,
    [address]               NVARCHAR (255) NULL,
    [city]                  NVARCHAR (255) NULL,
    [state]                 NVARCHAR (255) NULL,
    [zipcode]               NVARCHAR (255) NULL,
    [phone]                 NVARCHAR (255) NULL,
    [installer_id]          NVARCHAR (255) NULL,
    [latitude]              NVARCHAR (255) NULL,
    [longitude]             NVARCHAR (255) NULL,
    [Payable To First]      NVARCHAR (50)  NULL,
    [Payable To Last]       NVARCHAR (50)  NULL,
    [ImportDate]            DATETIME       DEFAULT (getdate()) NULL,
    [ImportFileName]        NVARCHAR (100) NULL,
    [Status]                NVARCHAR (15)  NULL,
    [AddressID]             INT            NULL,
    [ContactDetailsID]      INT            NULL,
    [SiteID]                INT            NULL
);

